### ISSUE TITLE
集成Spring Cache缓存 (结合使用Redis缓存技术)

### ISSUE THREAD

**Issue by yangjianze** [yangjianze/yjz-note#19]
集成前请看
[Redis集成](https://github.com/yangjianze/yjz-note/issues/17)
[Spring Cache集成](https://github.com/yangjianze/yjz-note/issues/18)

导入maven坐标

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-cache</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-redis</artifactId>
</dependency>
```

> 配置spplication.yml配置文件
```
spring:
  cache:
    redis:
      time-to-live: 1800000 #设置缓存过期时间，可选
```
